# Generated by Django 6.0.2 on 2026-03-23 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('ram', 'RAM'), ('storage', 'Storage'), ('motherboard', 'Motherboard'), ('psu', 'PSU'), ('case', 'Case'), ('cooling', 'Cooling')], max_length=20)),
                ('use_case', models.CharField(choices=[('gaming', 'Gaming'), ('students', 'Students'), ('it', 'IT'), ('creators', 'Creators')], max_length=20)),
                ('price', models.FloatField()),
                ('socket_type', models.CharField(blank=True, max_length=50)),
                ('ram_variant', models.CharField(blank=True, max_length=50)),
                ('power_draw', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(blank=True, max_length=200)),
                ('gpu', models.CharField(blank=True, max_length=200)),
                ('ram', models.CharField(blank=True, max_length=200)),
                ('motherboard', models.CharField(blank=True, max_length=200)),
                ('storage', models.CharField(blank=True, max_length=200)),
                ('psu', models.CharField(blank=True, max_length=200)),
                ('case', models.CharField(blank=True, max_length=200)),
                ('cooling', models.CharField(blank=True, max_length=200)),
                ('total_price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(blank=True, max_length=200)),
                ('gpu', models.CharField(blank=True, max_length=200)),
                ('ram', models.CharField(blank=True, max_length=200)),
                ('motherboard', models.CharField(blank=True, max_length=200)),
                ('storage', models.CharField(blank=True, max_length=200)),
                ('psu', models.CharField(blank=True, max_length=200)),
                ('case', models.CharField(blank=True, max_length=200)),
                ('cooling', models.CharField(blank=True, max_length=200)),
                ('total_price', models.FloatField(default=0)),
                ('customer_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('profit', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
